# Generated by Django 5.1.3 on 2024-11-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
    ]
